spring:
  application:
    name: tea-consumer
  profiles:
    active: dev
server:
  port: 8089
---
spring:
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka,http://localhost:7003/eureka
---
spring:
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka,http://localhost:7001/eureka
  
