spring:
  application:
    name: tea-eureka
  profiles:
    active: dev
server:
  port: 7003
---
spring:
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka
---
spring:
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka