spring:
  application:
    name: tea-provider
  profiles:
    active: dev
server:
  port: 8001
---
spring:
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
  instance:
    instance-id: teacher-provider-8001
    prefer-ip-address: true
info:
  name: teacher-provider
  version: 1.0.0
---
spring:
  profiles: test
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: teacher-provider-8001
    prefer-ip-address: true
info:
  name: teacher-provider-8001
  version: 1.0.0
